name: 'Common Paragraphs'
type: module
description: 'Configuration common paragraphs.'
recipes:
  - core/recipes/page_content_type
install:
  - link
  - paragraphs
config:
  actions:
    # Add the paragraphs field to the the page content type form display.
    core.entity_form_display.node.page.default:
      setComponent:
        name: field_page_pc_paragraphs
        options:
          type: entity_reference_paragraphs
          weight: 1
          region: content
          settings:
            title: Paragraph
            title_plural: Paragraphs
            edit_mode: open
            add_mode: dropdown
            form_display_mode: default
            default_paragraph_type: ''
          third_party_settings: { }
    # Update the page content type view display.
    core.entity_view_display.node.page.default:
      # Add the paragraphs field.
      setComponent:
        name: field_page_pc_paragraphs
        options:
          type: entity_reference_revisions_entity_view
          label: hidden
          settings:
            view_mode: default
            link: ''
          third_party_settings: { }
          weight: 2
          region: content
